workspace:
  base: /go
  path: src/github.com/udistrital/${DRONE_REPO##udistrital/}
  when:
      branch: [master]
      event: [push, pull_request]

pipeline:
   
  # upload app.zip to s3 bucket for CodePipline
  publish_s3:
    image: plugins/s3
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    region: "us-east-1"    
    bucket: "cliente-prod"
    source: /**/*
    target: /${DRONE_REPO_NAME%%_cliente}.portaloas.udistrital.edu.co
    strip_prefix: /
    when:
      branch: [master]
      event: [push, pull_request] 

  #Notify results to telegram
  notify_telegram:
    image: appleboy/drone-telegram
    secrets: [ telegram_token, telegram_to ]
    format: html
    message: >
      {{#success build.status}}
        <code>{{repo.owner}}/{{repo.name}}</code> <a href="{{build.link}}">SUCCESS</a>
        <code>{{commit.branch}}</code>@<a href="{{commit.link}}">{{truncate commit.sha 7}}</a>
      {{else}}
        <code>{{repo.owner}}/{{repo.name}}</code> <a href="{{build.link}}">FAILURE</a>
        <code>{{commit.branch}}</code>@<a href="{{commit.link}}">{{truncate commit.sha 7}}</a>
      {{/success}}
    when:
      status: [success, failure]
      branch: [master, test]
      event: [push, pull_request]      
  
