kind: pipeline
name: oas_cliente_ci

steps:
- name: cp_to_dist_release
  image: alpine:3.24
  commands:
  - mkdir dist
  - cp *.css dist
  - cp -r isotipos_aplicativos_svg dist/
  - cp -r logotipos_aplicativos_svg dist/
  - cp *.png dist
  - cp *.json dist
  - cp *.ttf dist
  when:
    branch:
    - release/*
    event:
    - push

- name: cp_to_dist_master
  image: alpine:3.24
  commands:
  - mkdir dist
  - cp *.css dist
  - cp *.png dist
  - cp -r isotipos_aplicativos_svg dist/
  - cp -r logotipos_aplicativos_svg dist/
  - cp *.json dist
  - cp *.ttf dist
  when:
    branch:
    - master
    event:
    - push

- name: publish_s3_release
  image: plugins/s3
  settings:
    bucket:
      from_secret: BUCKET_CLIENTES_TEST
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    region: us-east-1
    source: dist/**/*
    target: /${DRONE_REPO_NAME}
    strip_prefix: dist/
  when:
    branch:
    - release/*
    event:
    - push

- name: publish_s3_master
  image: plugins/s3
  settings:
    bucket:
      from_secret: BUCKET_CLIENTES_PROD
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    region: us-east-1
    source: dist/**/*
    target: /${DRONE_REPO_NAME}
    strip_prefix: dist/
  when:
    branch:
    - master
    event:
    - push
